// Code generated by counterfeiter. DO NOT EDIT.
package cachefakes

import (
	"context"
	"sync"

	cache "github.com/vinaycharlie01/nyro"
)

type MockCache struct {
	ClearStub        func(context.Context) error
	clearMutex       sync.RWMutex
	clearArgsForCall []struct {
		arg1 context.Context
	}
	clearReturns struct {
		result1 error
	}
	clearReturnsOnCall map[int]struct {
		result1 error
	}
	CloseStub        func() error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	closeReturns struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteStub        func(context.Context, any) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		arg1 context.Context
		arg2 any
	}
	deleteReturns struct {
		result1 error
	}
	deleteReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteMultiStub        func(context.Context, []any) error
	deleteMultiMutex       sync.RWMutex
	deleteMultiArgsForCall []struct {
		arg1 context.Context
		arg2 []any
	}
	deleteMultiReturns struct {
		result1 error
	}
	deleteMultiReturnsOnCall map[int]struct {
		result1 error
	}
	ExistsStub        func(context.Context, any) (bool, error)
	existsMutex       sync.RWMutex
	existsArgsForCall []struct {
		arg1 context.Context
		arg2 any
	}
	existsReturns struct {
		result1 bool
		result2 error
	}
	existsReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	GetStub        func(context.Context, any) (any, error)
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		arg1 context.Context
		arg2 any
	}
	getReturns struct {
		result1 any
		result2 error
	}
	getReturnsOnCall map[int]struct {
		result1 any
		result2 error
	}
	GetMultiStub        func(context.Context, []any) (map[any]any, error)
	getMultiMutex       sync.RWMutex
	getMultiArgsForCall []struct {
		arg1 context.Context
		arg2 []any
	}
	getMultiReturns struct {
		result1 map[any]any
		result2 error
	}
	getMultiReturnsOnCall map[int]struct {
		result1 map[any]any
		result2 error
	}
	GetOrSetStub        func(context.Context, any, func(context.Context) (any, error), ...cache.Option) (any, error)
	getOrSetMutex       sync.RWMutex
	getOrSetArgsForCall []struct {
		arg1 context.Context
		arg2 any
		arg3 func(context.Context) (any, error)
		arg4 []cache.Option
	}
	getOrSetReturns struct {
		result1 any
		result2 error
	}
	getOrSetReturnsOnCall map[int]struct {
		result1 any
		result2 error
	}
	GetStatsStub        func(context.Context) (*cache.Stats, error)
	getStatsMutex       sync.RWMutex
	getStatsArgsForCall []struct {
		arg1 context.Context
	}
	getStatsReturns struct {
		result1 *cache.Stats
		result2 error
	}
	getStatsReturnsOnCall map[int]struct {
		result1 *cache.Stats
		result2 error
	}
	HealthCheckStub        func(context.Context) error
	healthCheckMutex       sync.RWMutex
	healthCheckArgsForCall []struct {
		arg1 context.Context
	}
	healthCheckReturns struct {
		result1 error
	}
	healthCheckReturnsOnCall map[int]struct {
		result1 error
	}
	SetStub        func(context.Context, any, any, ...cache.Option) error
	setMutex       sync.RWMutex
	setArgsForCall []struct {
		arg1 context.Context
		arg2 any
		arg3 any
		arg4 []cache.Option
	}
	setReturns struct {
		result1 error
	}
	setReturnsOnCall map[int]struct {
		result1 error
	}
	SetMultiStub        func(context.Context, map[any]any, ...cache.Option) error
	setMultiMutex       sync.RWMutex
	setMultiArgsForCall []struct {
		arg1 context.Context
		arg2 map[any]any
		arg3 []cache.Option
	}
	setMultiReturns struct {
		result1 error
	}
	setMultiReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *MockCache) Clear(arg1 context.Context) error {
	fake.clearMutex.Lock()
	ret, specificReturn := fake.clearReturnsOnCall[len(fake.clearArgsForCall)]
	fake.clearArgsForCall = append(fake.clearArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ClearStub
	fakeReturns := fake.clearReturns
	fake.recordInvocation("Clear", []interface{}{arg1})
	fake.clearMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *MockCache) ClearCallCount() int {
	fake.clearMutex.RLock()
	defer fake.clearMutex.RUnlock()
	return len(fake.clearArgsForCall)
}

func (fake *MockCache) ClearCalls(stub func(context.Context) error) {
	fake.clearMutex.Lock()
	defer fake.clearMutex.Unlock()
	fake.ClearStub = stub
}

func (fake *MockCache) ClearArgsForCall(i int) context.Context {
	fake.clearMutex.RLock()
	defer fake.clearMutex.RUnlock()
	argsForCall := fake.clearArgsForCall[i]
	return argsForCall.arg1
}

func (fake *MockCache) ClearReturns(result1 error) {
	fake.clearMutex.Lock()
	defer fake.clearMutex.Unlock()
	fake.ClearStub = nil
	fake.clearReturns = struct {
		result1 error
	}{result1}
}

func (fake *MockCache) ClearReturnsOnCall(i int, result1 error) {
	fake.clearMutex.Lock()
	defer fake.clearMutex.Unlock()
	fake.ClearStub = nil
	if fake.clearReturnsOnCall == nil {
		fake.clearReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.clearReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *MockCache) Close() error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	stub := fake.CloseStub
	fakeReturns := fake.closeReturns
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *MockCache) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *MockCache) CloseCalls(stub func() error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *MockCache) CloseReturns(result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *MockCache) CloseReturnsOnCall(i int, result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *MockCache) Delete(arg1 context.Context, arg2 any) error {
	fake.deleteMutex.Lock()
	ret, specificReturn := fake.deleteReturnsOnCall[len(fake.deleteArgsForCall)]
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		arg1 context.Context
		arg2 any
	}{arg1, arg2})
	stub := fake.DeleteStub
	fakeReturns := fake.deleteReturns
	fake.recordInvocation("Delete", []interface{}{arg1, arg2})
	fake.deleteMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *MockCache) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *MockCache) DeleteCalls(stub func(context.Context, any) error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = stub
}

func (fake *MockCache) DeleteArgsForCall(i int) (context.Context, any) {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	argsForCall := fake.deleteArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *MockCache) DeleteReturns(result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *MockCache) DeleteReturnsOnCall(i int, result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	if fake.deleteReturnsOnCall == nil {
		fake.deleteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *MockCache) DeleteMulti(arg1 context.Context, arg2 []any) error {
	var arg2Copy []any
	if arg2 != nil {
		arg2Copy = make([]any, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.deleteMultiMutex.Lock()
	ret, specificReturn := fake.deleteMultiReturnsOnCall[len(fake.deleteMultiArgsForCall)]
	fake.deleteMultiArgsForCall = append(fake.deleteMultiArgsForCall, struct {
		arg1 context.Context
		arg2 []any
	}{arg1, arg2Copy})
	stub := fake.DeleteMultiStub
	fakeReturns := fake.deleteMultiReturns
	fake.recordInvocation("DeleteMulti", []interface{}{arg1, arg2Copy})
	fake.deleteMultiMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *MockCache) DeleteMultiCallCount() int {
	fake.deleteMultiMutex.RLock()
	defer fake.deleteMultiMutex.RUnlock()
	return len(fake.deleteMultiArgsForCall)
}

func (fake *MockCache) DeleteMultiCalls(stub func(context.Context, []any) error) {
	fake.deleteMultiMutex.Lock()
	defer fake.deleteMultiMutex.Unlock()
	fake.DeleteMultiStub = stub
}

func (fake *MockCache) DeleteMultiArgsForCall(i int) (context.Context, []any) {
	fake.deleteMultiMutex.RLock()
	defer fake.deleteMultiMutex.RUnlock()
	argsForCall := fake.deleteMultiArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *MockCache) DeleteMultiReturns(result1 error) {
	fake.deleteMultiMutex.Lock()
	defer fake.deleteMultiMutex.Unlock()
	fake.DeleteMultiStub = nil
	fake.deleteMultiReturns = struct {
		result1 error
	}{result1}
}

func (fake *MockCache) DeleteMultiReturnsOnCall(i int, result1 error) {
	fake.deleteMultiMutex.Lock()
	defer fake.deleteMultiMutex.Unlock()
	fake.DeleteMultiStub = nil
	if fake.deleteMultiReturnsOnCall == nil {
		fake.deleteMultiReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteMultiReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *MockCache) Exists(arg1 context.Context, arg2 any) (bool, error) {
	fake.existsMutex.Lock()
	ret, specificReturn := fake.existsReturnsOnCall[len(fake.existsArgsForCall)]
	fake.existsArgsForCall = append(fake.existsArgsForCall, struct {
		arg1 context.Context
		arg2 any
	}{arg1, arg2})
	stub := fake.ExistsStub
	fakeReturns := fake.existsReturns
	fake.recordInvocation("Exists", []interface{}{arg1, arg2})
	fake.existsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *MockCache) ExistsCallCount() int {
	fake.existsMutex.RLock()
	defer fake.existsMutex.RUnlock()
	return len(fake.existsArgsForCall)
}

func (fake *MockCache) ExistsCalls(stub func(context.Context, any) (bool, error)) {
	fake.existsMutex.Lock()
	defer fake.existsMutex.Unlock()
	fake.ExistsStub = stub
}

func (fake *MockCache) ExistsArgsForCall(i int) (context.Context, any) {
	fake.existsMutex.RLock()
	defer fake.existsMutex.RUnlock()
	argsForCall := fake.existsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *MockCache) ExistsReturns(result1 bool, result2 error) {
	fake.existsMutex.Lock()
	defer fake.existsMutex.Unlock()
	fake.ExistsStub = nil
	fake.existsReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *MockCache) ExistsReturnsOnCall(i int, result1 bool, result2 error) {
	fake.existsMutex.Lock()
	defer fake.existsMutex.Unlock()
	fake.ExistsStub = nil
	if fake.existsReturnsOnCall == nil {
		fake.existsReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.existsReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *MockCache) Get(arg1 context.Context, arg2 any) (any, error) {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		arg1 context.Context
		arg2 any
	}{arg1, arg2})
	stub := fake.GetStub
	fakeReturns := fake.getReturns
	fake.recordInvocation("Get", []interface{}{arg1, arg2})
	fake.getMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *MockCache) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *MockCache) GetCalls(stub func(context.Context, any) (any, error)) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = stub
}

func (fake *MockCache) GetArgsForCall(i int) (context.Context, any) {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	argsForCall := fake.getArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *MockCache) GetReturns(result1 any, result2 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 any
		result2 error
	}{result1, result2}
}

func (fake *MockCache) GetReturnsOnCall(i int, result1 any, result2 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 any
			result2 error
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 any
		result2 error
	}{result1, result2}
}

func (fake *MockCache) GetMulti(arg1 context.Context, arg2 []any) (map[any]any, error) {
	var arg2Copy []any
	if arg2 != nil {
		arg2Copy = make([]any, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.getMultiMutex.Lock()
	ret, specificReturn := fake.getMultiReturnsOnCall[len(fake.getMultiArgsForCall)]
	fake.getMultiArgsForCall = append(fake.getMultiArgsForCall, struct {
		arg1 context.Context
		arg2 []any
	}{arg1, arg2Copy})
	stub := fake.GetMultiStub
	fakeReturns := fake.getMultiReturns
	fake.recordInvocation("GetMulti", []interface{}{arg1, arg2Copy})
	fake.getMultiMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *MockCache) GetMultiCallCount() int {
	fake.getMultiMutex.RLock()
	defer fake.getMultiMutex.RUnlock()
	return len(fake.getMultiArgsForCall)
}

func (fake *MockCache) GetMultiCalls(stub func(context.Context, []any) (map[any]any, error)) {
	fake.getMultiMutex.Lock()
	defer fake.getMultiMutex.Unlock()
	fake.GetMultiStub = stub
}

func (fake *MockCache) GetMultiArgsForCall(i int) (context.Context, []any) {
	fake.getMultiMutex.RLock()
	defer fake.getMultiMutex.RUnlock()
	argsForCall := fake.getMultiArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *MockCache) GetMultiReturns(result1 map[any]any, result2 error) {
	fake.getMultiMutex.Lock()
	defer fake.getMultiMutex.Unlock()
	fake.GetMultiStub = nil
	fake.getMultiReturns = struct {
		result1 map[any]any
		result2 error
	}{result1, result2}
}

func (fake *MockCache) GetMultiReturnsOnCall(i int, result1 map[any]any, result2 error) {
	fake.getMultiMutex.Lock()
	defer fake.getMultiMutex.Unlock()
	fake.GetMultiStub = nil
	if fake.getMultiReturnsOnCall == nil {
		fake.getMultiReturnsOnCall = make(map[int]struct {
			result1 map[any]any
			result2 error
		})
	}
	fake.getMultiReturnsOnCall[i] = struct {
		result1 map[any]any
		result2 error
	}{result1, result2}
}

func (fake *MockCache) GetOrSet(arg1 context.Context, arg2 any, arg3 func(context.Context) (any, error), arg4 ...cache.Option) (any, error) {
	fake.getOrSetMutex.Lock()
	ret, specificReturn := fake.getOrSetReturnsOnCall[len(fake.getOrSetArgsForCall)]
	fake.getOrSetArgsForCall = append(fake.getOrSetArgsForCall, struct {
		arg1 context.Context
		arg2 any
		arg3 func(context.Context) (any, error)
		arg4 []cache.Option
	}{arg1, arg2, arg3, arg4})
	stub := fake.GetOrSetStub
	fakeReturns := fake.getOrSetReturns
	fake.recordInvocation("GetOrSet", []interface{}{arg1, arg2, arg3, arg4})
	fake.getOrSetMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *MockCache) GetOrSetCallCount() int {
	fake.getOrSetMutex.RLock()
	defer fake.getOrSetMutex.RUnlock()
	return len(fake.getOrSetArgsForCall)
}

func (fake *MockCache) GetOrSetCalls(stub func(context.Context, any, func(context.Context) (any, error), ...cache.Option) (any, error)) {
	fake.getOrSetMutex.Lock()
	defer fake.getOrSetMutex.Unlock()
	fake.GetOrSetStub = stub
}

func (fake *MockCache) GetOrSetArgsForCall(i int) (context.Context, any, func(context.Context) (any, error), []cache.Option) {
	fake.getOrSetMutex.RLock()
	defer fake.getOrSetMutex.RUnlock()
	argsForCall := fake.getOrSetArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *MockCache) GetOrSetReturns(result1 any, result2 error) {
	fake.getOrSetMutex.Lock()
	defer fake.getOrSetMutex.Unlock()
	fake.GetOrSetStub = nil
	fake.getOrSetReturns = struct {
		result1 any
		result2 error
	}{result1, result2}
}

func (fake *MockCache) GetOrSetReturnsOnCall(i int, result1 any, result2 error) {
	fake.getOrSetMutex.Lock()
	defer fake.getOrSetMutex.Unlock()
	fake.GetOrSetStub = nil
	if fake.getOrSetReturnsOnCall == nil {
		fake.getOrSetReturnsOnCall = make(map[int]struct {
			result1 any
			result2 error
		})
	}
	fake.getOrSetReturnsOnCall[i] = struct {
		result1 any
		result2 error
	}{result1, result2}
}

func (fake *MockCache) GetStats(arg1 context.Context) (*cache.Stats, error) {
	fake.getStatsMutex.Lock()
	ret, specificReturn := fake.getStatsReturnsOnCall[len(fake.getStatsArgsForCall)]
	fake.getStatsArgsForCall = append(fake.getStatsArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetStatsStub
	fakeReturns := fake.getStatsReturns
	fake.recordInvocation("GetStats", []interface{}{arg1})
	fake.getStatsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *MockCache) GetStatsCallCount() int {
	fake.getStatsMutex.RLock()
	defer fake.getStatsMutex.RUnlock()
	return len(fake.getStatsArgsForCall)
}

func (fake *MockCache) GetStatsCalls(stub func(context.Context) (*cache.Stats, error)) {
	fake.getStatsMutex.Lock()
	defer fake.getStatsMutex.Unlock()
	fake.GetStatsStub = stub
}

func (fake *MockCache) GetStatsArgsForCall(i int) context.Context {
	fake.getStatsMutex.RLock()
	defer fake.getStatsMutex.RUnlock()
	argsForCall := fake.getStatsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *MockCache) GetStatsReturns(result1 *cache.Stats, result2 error) {
	fake.getStatsMutex.Lock()
	defer fake.getStatsMutex.Unlock()
	fake.GetStatsStub = nil
	fake.getStatsReturns = struct {
		result1 *cache.Stats
		result2 error
	}{result1, result2}
}

func (fake *MockCache) GetStatsReturnsOnCall(i int, result1 *cache.Stats, result2 error) {
	fake.getStatsMutex.Lock()
	defer fake.getStatsMutex.Unlock()
	fake.GetStatsStub = nil
	if fake.getStatsReturnsOnCall == nil {
		fake.getStatsReturnsOnCall = make(map[int]struct {
			result1 *cache.Stats
			result2 error
		})
	}
	fake.getStatsReturnsOnCall[i] = struct {
		result1 *cache.Stats
		result2 error
	}{result1, result2}
}

func (fake *MockCache) HealthCheck(arg1 context.Context) error {
	fake.healthCheckMutex.Lock()
	ret, specificReturn := fake.healthCheckReturnsOnCall[len(fake.healthCheckArgsForCall)]
	fake.healthCheckArgsForCall = append(fake.healthCheckArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.HealthCheckStub
	fakeReturns := fake.healthCheckReturns
	fake.recordInvocation("HealthCheck", []interface{}{arg1})
	fake.healthCheckMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *MockCache) HealthCheckCallCount() int {
	fake.healthCheckMutex.RLock()
	defer fake.healthCheckMutex.RUnlock()
	return len(fake.healthCheckArgsForCall)
}

func (fake *MockCache) HealthCheckCalls(stub func(context.Context) error) {
	fake.healthCheckMutex.Lock()
	defer fake.healthCheckMutex.Unlock()
	fake.HealthCheckStub = stub
}

func (fake *MockCache) HealthCheckArgsForCall(i int) context.Context {
	fake.healthCheckMutex.RLock()
	defer fake.healthCheckMutex.RUnlock()
	argsForCall := fake.healthCheckArgsForCall[i]
	return argsForCall.arg1
}

func (fake *MockCache) HealthCheckReturns(result1 error) {
	fake.healthCheckMutex.Lock()
	defer fake.healthCheckMutex.Unlock()
	fake.HealthCheckStub = nil
	fake.healthCheckReturns = struct {
		result1 error
	}{result1}
}

func (fake *MockCache) HealthCheckReturnsOnCall(i int, result1 error) {
	fake.healthCheckMutex.Lock()
	defer fake.healthCheckMutex.Unlock()
	fake.HealthCheckStub = nil
	if fake.healthCheckReturnsOnCall == nil {
		fake.healthCheckReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.healthCheckReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *MockCache) Set(arg1 context.Context, arg2 any, arg3 any, arg4 ...cache.Option) error {
	fake.setMutex.Lock()
	ret, specificReturn := fake.setReturnsOnCall[len(fake.setArgsForCall)]
	fake.setArgsForCall = append(fake.setArgsForCall, struct {
		arg1 context.Context
		arg2 any
		arg3 any
		arg4 []cache.Option
	}{arg1, arg2, arg3, arg4})
	stub := fake.SetStub
	fakeReturns := fake.setReturns
	fake.recordInvocation("Set", []interface{}{arg1, arg2, arg3, arg4})
	fake.setMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *MockCache) SetCallCount() int {
	fake.setMutex.RLock()
	defer fake.setMutex.RUnlock()
	return len(fake.setArgsForCall)
}

func (fake *MockCache) SetCalls(stub func(context.Context, any, any, ...cache.Option) error) {
	fake.setMutex.Lock()
	defer fake.setMutex.Unlock()
	fake.SetStub = stub
}

func (fake *MockCache) SetArgsForCall(i int) (context.Context, any, any, []cache.Option) {
	fake.setMutex.RLock()
	defer fake.setMutex.RUnlock()
	argsForCall := fake.setArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *MockCache) SetReturns(result1 error) {
	fake.setMutex.Lock()
	defer fake.setMutex.Unlock()
	fake.SetStub = nil
	fake.setReturns = struct {
		result1 error
	}{result1}
}

func (fake *MockCache) SetReturnsOnCall(i int, result1 error) {
	fake.setMutex.Lock()
	defer fake.setMutex.Unlock()
	fake.SetStub = nil
	if fake.setReturnsOnCall == nil {
		fake.setReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.setReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *MockCache) SetMulti(arg1 context.Context, arg2 map[any]any, arg3 ...cache.Option) error {
	fake.setMultiMutex.Lock()
	ret, specificReturn := fake.setMultiReturnsOnCall[len(fake.setMultiArgsForCall)]
	fake.setMultiArgsForCall = append(fake.setMultiArgsForCall, struct {
		arg1 context.Context
		arg2 map[any]any
		arg3 []cache.Option
	}{arg1, arg2, arg3})
	stub := fake.SetMultiStub
	fakeReturns := fake.setMultiReturns
	fake.recordInvocation("SetMulti", []interface{}{arg1, arg2, arg3})
	fake.setMultiMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *MockCache) SetMultiCallCount() int {
	fake.setMultiMutex.RLock()
	defer fake.setMultiMutex.RUnlock()
	return len(fake.setMultiArgsForCall)
}

func (fake *MockCache) SetMultiCalls(stub func(context.Context, map[any]any, ...cache.Option) error) {
	fake.setMultiMutex.Lock()
	defer fake.setMultiMutex.Unlock()
	fake.SetMultiStub = stub
}

func (fake *MockCache) SetMultiArgsForCall(i int) (context.Context, map[any]any, []cache.Option) {
	fake.setMultiMutex.RLock()
	defer fake.setMultiMutex.RUnlock()
	argsForCall := fake.setMultiArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *MockCache) SetMultiReturns(result1 error) {
	fake.setMultiMutex.Lock()
	defer fake.setMultiMutex.Unlock()
	fake.SetMultiStub = nil
	fake.setMultiReturns = struct {
		result1 error
	}{result1}
}

func (fake *MockCache) SetMultiReturnsOnCall(i int, result1 error) {
	fake.setMultiMutex.Lock()
	defer fake.setMultiMutex.Unlock()
	fake.SetMultiStub = nil
	if fake.setMultiReturnsOnCall == nil {
		fake.setMultiReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.setMultiReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *MockCache) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *MockCache) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cache.Cache = new(MockCache)
